### ISSUE TITLE
ModelBase API Reference seems broken

### ISSUE THREAD

**Issue by samirem** [Catel/Catel.Docs#1]
See the following link:
http://docs.catelproject.com/vnext/reference/catel-core/catel/data/modelbase/index.htm

**Comment by GeertvanHorrik** [comment]
Good catch. This is the reference documentation. We'll look into this.

**Comment by GeertvanHorrik** [comment]
We've moved to Hugo for the site generation, but it still has some issues.

**Comment by GeertvanHorrik** [comment]
btw here is the new url:

http://docs.catelproject.com/vnext/reference/catel.core/catel/data/modelbase/

**Comment by samirem** [comment]
Looks neat. `ModelBase` still not rendering though, right?

**Comment by GeertvanHorrik** [comment]
Correct, it's still not rendering correctly. I'll investigate this weekend.

**Comment by GeertvanHorrik** [comment]
Should be fixed, site is to be expected to be updated in 15 minutes or so.
