### ISSUE TITLE
Tables in the documentation broken

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Catel/Catel.Docs#9]
Several pages which use tables seem to be broken, for example:

http://docs.catelproject.com/5.8/setup-deployment/code-snippets-templates/using-the-code-snippets/

Seems that the site generator doesn't know about markdown tables.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we will look into this.

**Comment by GeertvanHorrik** [comment]
Found this ticket. Maybe I should update.

https://github.com/gohugoio/hugo/issues/3525

**Comment by GeertvanHorrik** [comment]
This is fixed for vNext (5.9) and above.
